#if !canImport(ObjectiveC)
import XCTest

extension CodeGenTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CodeGenTests = [
        ("testPlatformConstants", testPlatformConstants),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CodeGenTests.__allTests__CodeGenTests),
    ]
}
#endif
